# Generated by Django 4.2.27 on 2025-12-05 05:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('READER', 'Reader'), ('EDITOR', 'Editor'), ('JOURNALIST', 'Journalist')], default='READER', help_text="User's role in the system", max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('journalist_subscriptions', models.ManyToManyField(blank=True, help_text='Journalists this reader subscribes to', limit_choices_to={'role': 'JOURNALIST'}, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the publisher', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the publisher')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the publisher was created')),
                ('editors', models.ManyToManyField(blank=True, help_text='Editors associated with this publisher', limit_choices_to={'role': 'EDITOR'}, related_name='publishers_editing', to=settings.AUTH_USER_MODEL)),
                ('journalists', models.ManyToManyField(blank=True, help_text='Journalists associated with this publisher', limit_choices_to={'role': 'JOURNALIST'}, related_name='publishers_writing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the newsletter', max_length=200)),
                ('content', models.TextField(help_text='Content of the newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the newsletter was created')),
                ('author', models.ForeignKey(help_text='Journalist who created this newsletter', limit_choices_to={'role': 'JOURNALIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_newsletters', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(blank=True, help_text='Publisher associated with this newsletter (null for independent newsletters)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='news.publisher')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='publisher_subscriptions',
            field=models.ManyToManyField(blank=True, help_text='Publishers this reader subscribes to', related_name='subscribers', to='news.publisher'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the article', max_length=200)),
                ('content', models.TextField(help_text='Full content of the article')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this article has been approved by an editor')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the article was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the article was last updated')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Editor who approved this article', limit_choices_to={'role': 'EDITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(help_text='Journalist who wrote this article', limit_choices_to={'role': 'JOURNALIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(blank=True, help_text='Publisher associated with this article (null for independent articles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.publisher')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='news_articl_created_a034b3_idx'), models.Index(fields=['is_approved'], name='news_articl_is_appr_8164f3_idx'), models.Index(fields=['author'], name='news_articl_author__94d1eb_idx')],
            },
        ),
    ]
